# 初始化数据

In [121]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import pymysql

In [122]:
header = ['user_id', 'item_id','rating', 'timestamp']

In [123]:
df = pd.read_csv('data/recommender_system.data', sep='\t', names=header)

In [124]:
user_number = df.user_id.unique().shape[0]

In [125]:
item_number = df.item_id.unique().shape[0]

In [126]:
print('Number of users is: %i, Number of item is %i'% (user_number,item_number))

Number of users is: 943, Number of item is 1682


# 分离样本的训练集和验证集

In [127]:
from sklearn import cross_validation

In [128]:
train_data, test_data = cross_validation.train_test_split(df, test_size=0.3)

In [129]:
train_matrix = np.zeros((user_number,item_number))

In [130]:
for row in train_data.itertuples():
    train_matrix[row[1]-1,row[2]-1] = row[3]

In [131]:
test_matrix = np.zeros((user_number,item_number))

In [132]:
for row in test_data.itertuples():
    test_matrix[row[1]-1,row[2]-1] = row [3]

In [133]:
train_matrix

array([[ 5.,  3.,  0., ...,  0.,  0.,  0.],
       [ 4.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 5.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  5.,  0., ...,  0.,  0.,  0.]])

In [134]:
test_matrix

array([[ 0.,  0.,  4., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

# 推荐

In [135]:
from sklearn.metrics.pairwise import pairwise_distances as pairdis

In [136]:
user_similarity = pairdis(train_matrix, metric='cosine')

In [137]:
item_similarity = pairdis(train_matrix.T, metric='cosine')

In [138]:
mean_user_rating = train_matrix.mean(axis=1)

In [139]:
ratings_diff = (train_matrix - mean_user_rating[:,np.newaxis])

In [140]:
user_based_prediction = mean_user_rating[:,np.newaxis] + user_similarity.dot(ratings_diff) / np.array([np.abs(user_similarity).sum(axis=1)]).T

In [141]:
item_based_prediction = train_matrix.dot(item_similarity) / np.array([np.abs(item_similarity).sum(axis=1)])

# 结果存入数据库

In [142]:
data = pd.DataFrame(item_based_prediction)

In [143]:
data

0         1         2         3         4         5         6     \
0    0.352424  0.364482  0.388982  0.349351  0.380148  0.392862  0.354097   
1    0.075137  0.086134  0.084571  0.083024  0.084646  0.084642  0.077039   
2    0.070493  0.073817  0.071177  0.073047  0.071243  0.072574  0.069290   
3    0.040444  0.042753  0.041928  0.042357  0.042197  0.043971  0.040477   
4    0.156782  0.155096  0.170914  0.154665  0.170301  0.183803  0.160013   
5    0.277808  0.304722  0.315990  0.285983  0.312822  0.316302  0.282614   
6    0.576925  0.588543  0.622903  0.560933  0.613210  0.645482  0.572830   
7    0.069022  0.070232  0.078703  0.068302  0.076933  0.085446  0.068047   
8    0.031208  0.033729  0.034626  0.032497  0.034405  0.031565  0.029749   
9    0.253552  0.269448  0.282740  0.250739  0.278164  0.286048  0.258341   
10   0.224107  0.230819  0.240900  0.222082  0.239003  0.251935  0.225750   
11   0.078029  0.084663  0.090756  0.075951  0.089660  0.097192  0.082363   
12   0.774331  0.781947  0.823401  0.775170  0.809537  0.842624  0.779095   
13   0.137288  0.150501  0.153043  0.138089  0.153808  0.156897  0.132926   
14   0.121895  0.134715  0.133036  0.134523  0.134693  0.137944  0.124775   
15   0.203961  0.215178  0.230774  0.197573  0.225839  0.246679  0.207743   
16   0.029470  0.036770  0.035783  0.034704  0.036600  0.037511  0.028839   
17   0.395777  0.423410  0.443219  0.396007  0.435961  0.428222  0.406451   
18   0.022127  0.024026  0.024194  0.022452  0.024101  0.025515  0.022198   
19   0.040339  0.045224  0.047948  0.043536  0.047427  0.053786  0.042531   
20   0.194201  0.205006  0.203431  0.203192  0.196158  0.212011  0.187958   
21   0.165252  0.165025  0.184640  0.156861  0.181653  0.199142  0.168448   
22   0.177318  0.187157  0.199688  0.176980  0.194812  0.205252  0.176738   
23   0.108765  0.118893  0.120990  0.109687  0.122393  0.130849  0.105879   
24   0.102736  0.115020  0.123755  0.108778  0.122146  0.129505  0.106362   
25   0.112019  0.127687  0.122321  0.123574  0.127252  0.132674  0.111051   
26   0.030429  0.034789  0.032931  0.034137  0.034006  0.035860  0.029888   
27   0.098687  0.103053  0.110270  0.098974  0.104625  0.118944  0.094827   
28   0.056586  0.059189  0.059330  0.058321  0.059145  0.060772  0.056366   
29   0.064878  0.068056  0.072655  0.069031  0.072046  0.075448  0.063857   
..        ...       ...       ...       ...       ...       ...       ...   
913  0.031497  0.031422  0.033724  0.030435  0.032175  0.033520  0.032869   
914  0.034645  0.036093  0.035336  0.035461  0.035547  0.035205  0.034399   
915  0.375257  0.389402  0.404190  0.372552  0.399111  0.427559  0.373018   
916  0.039207  0.046296  0.043311  0.044829  0.045404  0.046917  0.040590   
917  0.134562  0.141626  0.146509  0.135904  0.145721  0.143354  0.139229   
918  0.261924  0.282579  0.283347  0.271932  0.276791  0.293572  0.259899   
919  0.026222  0.027655  0.026681  0.026727  0.026291  0.026957  0.025440   
920  0.117133  0.128574  0.134280  0.125657  0.133889  0.145510  0.123724   
921  0.134877  0.135144  0.147006  0.131868  0.146369  0.162027  0.137053   
922  0.114572  0.128205  0.118380  0.125458  0.128713  0.137194  0.114746   
923  0.110830  0.119004  0.127324  0.114451  0.126605  0.126686  0.110444   
924  0.040242  0.041839  0.041697  0.040791  0.036283  0.044460  0.038503   
925  0.018477  0.020717  0.020018  0.019805  0.020105  0.020858  0.018496   
926  0.170504  0.180455  0.190417  0.179498  0.192374  0.212387  0.178140   
927  0.054067  0.056336  0.058861  0.055310  0.057443  0.058666  0.054717   
928  0.059811  0.064082  0.069786  0.059620  0.068873  0.071519  0.060181   
929  0.062123  0.071517  0.070792  0.068023  0.072408  0.074069  0.064173   
930  0.087607  0.098097  0.095601  0.094666  0.097794  0.098022  0.088031   
931  0.363984  0.381274  0.403358  0.368040  0.393826  0.404514  0.366026   
932  0.145983  0.151353  0.166873  0.141563  0.163958  0.180216  0.149829   
933  

In [144]:
data_t = data.T

In [145]:
result_top_value = list()

In [146]:
for i in data_t:
    result_top_value.append(data_t[i].sort_values().head(5))    

In [147]:
result_top_value

[97     0.336737
 194    0.337009
 167    0.338877
 88     0.339516
 203    0.339691
 Name: 0, dtype: float64, 285    0.070275
 268    0.072096
 236    0.072492
 301    0.072502
 257    0.072791
 Name: 1, dtype: float64, 327    0.058965
 306    0.059005
 330    0.059185
 326    0.059188
 299    0.059249
 Name: 2, dtype: float64, 299    0.033309
 293    0.034604
 358    0.034620
 326    0.034769
 287    0.035038
 Name: 3, dtype: float64, 167    0.145904
 173    0.145977
 209    0.146025
 226    0.146697
 171    0.146935
 Name: 4, dtype: float64, 482    0.259677
 190    0.261588
 134    0.263240
 97     0.264009
 173    0.264100
 Name: 5, dtype: float64, 203    0.540265
 194    0.540497
 233    0.541976
 182    0.542436
 97     0.544501
 Name: 6, dtype: float64, 194    0.059199
 173    0.059585
 95     0.060410
 175    0.060665
 182    0.061141
 Name: 7, dtype: float64, 49     0.028469
 482    0.029405
 6      0.029749
 275    0.030268
 370    0.030416
 Name: 8, dtype: float64, 97     0.

In [148]:
# 打开数据库连接
db = pymysql.connect("localhost","root","asdf","test" )
# 使用 cursor() 方法创建一个游标对象 cursor
cursor = db.cursor()
cursor.execute("truncate table user_pefer")
try:
    for row in result_top_value:
            sql = 'insert into user_pefer(user_id,product_id,score) values (%i,%i,%f)'%(row.name,index,row[index])
            print(sql)
            cursor.execute(sql)
            db.commit()
        print('=======')
except:
    print ("Error: unable to fetch data")
    db.rollback()
# db.close()

insert into user_pefer(user_id,product_id,score) values (0,97,0.336737)
insert into user_pefer(user_id,product_id,score) values (0,194,0.337009)
insert into user_pefer(user_id,product_id,score) values (0,167,0.338877)
insert into user_pefer(user_id,product_id,score) values (0,88,0.339516)
insert into user_pefer(user_id,product_id,score) values (0,203,0.339691)
insert into user_pefer(user_id,product_id,score) values (1,285,0.070275)
insert into user_pefer(user_id,product_id,score) values (1,268,0.072096)
insert into user_pefer(user_id,product_id,score) values (1,236,0.072492)
insert into user_pefer(user_id,product_id,score) values (1,301,0.072502)
insert into user_pefer(user_id,product_id,score) values (1,257,0.072791)
insert into user_pefer(user_id,product_id,score) values (2,327,0.058965)
insert into user_pefer(user_id,product_id,score) values (2,306,0.059005)
insert into user_pefer(user_id,product_id,score) values (2,330,0.059185)
insert into user_pefer(user_id,product_id,score) valu

# 结果评估

In [149]:
from sklearn.metrics import mean_squared_error

In [150]:
from math import sqrt

In [151]:
user_based_prediction = user_based_prediction[test_matrix.nonzero()].flatten()

In [152]:
test_matrix_flatten = test_matrix[test_matrix.nonzero()].flatten()

In [153]:
sqrt(mean_squared_error(user_based_prediction, test_matrix_flatten))

3.160537516852938

In [154]:
item_based_prediction = item_based_prediction[test_matrix.nonzero()].flatten()

In [155]:
sqrt(mean_squared_error(item_based_prediction, test_matrix_flatten))

3.4667759356901495

# 基于SVD的最大似然法

In [156]:
#稀疏度
sparsity = 1.0-(len(df)/float(user_number*item_number))
sparsity

0.9369533063577546

In [157]:
from scipy.sparse.linalg import svds

In [158]:
u, s, v = svds(train_matrix, k=30)

In [159]:
s_matrix = np.diag(s)

In [160]:
SVD_prediction = np.dot(np.dot(u, s_matrix), v)

In [161]:
SVD_prediction = SVD_prediction[test_matrix.nonzero()].flatten()

In [162]:
sqrt(mean_squared_error(SVD_prediction, test_matrix_flatten))

2.870914805780211

In [163]:
SVD_prediction

array([ 0.26384505,  0.70201396,  1.80005597, ...,  0.18969044,
        0.73005727,  0.63351654])

In [164]:
save_frame = pd.DataFrame(data=np.dot(np.dot(u, s_matrix), v),)

In [165]:
save_frame.to_csv('save_data')